# Configure.
language: python
python: 3.5
sudo: false

# Run.
install: pip install appveyor-artifacts coveralls tox
before_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
script: tox -e lint,py35,py34,py33,pypy,py27,docs
after_success:
  - coveralls

# Deploy.
deploy:
  provider: pypi
  user: Robpol86
  password:
    secure:
      "SL9UOy/1SkvG3t5K1kRjN8OPLoP8OR6DAw5hiWkUBaqRsqvWh3YJep6uECQ20gYAU5HXgLJ\
      Jug1LCUqiJ52JBCHbrc5rWy0XqfxwhG2euMfT3D3D527URthifchECNIhJpYDffuiCT5m4VR\
      zg35E98UoiFAWpTHvyzO33JyP5ZWXrlEI1HYXRwS9fosJSsTNnzc5u4fraQs1mjCWSwRrS6+\
      HUbbNY0NygQ7wwL4KIjn9/h1C3X4nqwBqgFt9Ed6yvQgXh3OMv/rseA6oko9Iw3pVJZR5emU\
      sejcQ1txJ4EMbahcdWJFo4xpYy2VNxRAyQWtav4IWST19bGmhQB1Cgn2WBW7PQswYev+IZ7Z\
      FS1L3OXFItUuS7IV/uOTnMPetD1WqIrVlPHy+N4Sy30QBoZPDO6/DlknPK4dDXhmb+atrVCZ\
      z8y2Ol06QEwM8Ewmn+ch+Hez9dxLsD5TczHSYMrz/c/AloHqr+3lZDJ+hr0D2vvnerqLqJvH\
      Mp5p+vwnYNtpSInlYNLvcUITpQaOaqBzkFiJ+mIFoswsPhfw15gGZ0akIvVT9YAqJ2eeMrGx\
      kzxiCBVD4dqGxMh318BmwXdurgWZbia2DJWs+QBNs44kiSByQmXWFXo2KamiBZAez+AdBPgA\
      Hs/smp3nE3TI9cHQzzbhDFZftI4dtLf8osNI="
  on:
    tags: true
