# Configure.
language: python
python: 3.5
sudo: false

# Run.
install: pip install appveyor-artifacts coveralls tox
before_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
script: tox -e lint,py35,py34,py33,pypy,py27,docs
after_success:
  - coveralls

# Deploy.
deploy:
  provider: pypi
  user: Robpol86
  password:
    secure:
      "multi\
      line\
      encrypted"
  on:
    tags: true
